# GraphvizForGAP, chapter 2
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("graphvizforgap01.tst");

# doc/_Chapter_Full_Reference.xml:78-89
gap> gv := GraphvizGraph("GraphyMcGraphFace");
<graphviz graph "GraphyMcGraphFace" with 0 nodes and 0 edges>
gap> GraphvizName(gv);
"GraphyMcGraphFace"
gap> GraphvizGraph(666);
<graphviz graph "666" with 0 nodes and 0 edges>
gap> gv := GraphvizGraph();
<graphviz graph with 0 nodes and 0 edges>
gap> GraphvizName(gv);
""

# doc/_Chapter_Full_Reference.xml:131-142
gap> gv := GraphvizDigraph("GraphyMcGraphFace");
<graphviz digraph "GraphyMcGraphFace" with 0 nodes and 0 edges>
gap> GraphvizName(gv);
"GraphyMcGraphFace"
gap> GraphvizDigraph(666);
<graphviz digraph "666" with 0 nodes and 0 edges>
gap> gv := GraphvizDigraph();
<graphviz digraph with 0 nodes and 0 edges>
gap> GraphvizName(gv);
""

# doc/_Chapter_Full_Reference.xml:167-178
gap> dot := GraphvizDigraph("The Round Table");;
gap> GraphvizName(dot);
"The Round Table"
gap> n := GraphvizSetAttr(GraphvizAddNode(dot, "A"), "label", "King Arthur");
<graphviz node "A">
gap> GraphvizName(n);
"A"
gap> e := GraphvizAddEdge(dot, "A", "B");;
gap> GraphvizName(e);
"(A, B)"

# doc/_Chapter_Full_Reference.xml:191-192

# doc/_Chapter_Full_Reference.xml:211-212

# doc/_Chapter_Full_Reference.xml:226-227

# doc/_Chapter_Full_Reference.xml:240-241

# doc/_Chapter_Full_Reference.xml:255-256

# doc/_Chapter_Full_Reference.xml:272-273

# doc/_Chapter_Full_Reference.xml:290-297
gap> gv := GraphvizGraph();;
gap> GraphvizAddEdge(gv, "a", "b");;
gap> GraphvizEdges(gv);
[ <graphviz edge (a, b)> ]
gap> GraphvizEdges(gv, "a", "b");
[ <graphviz edge (a, b)> ]

# doc/_Chapter_Full_Reference.xml:311-317
gap> gv := GraphvizGraph();;
gap> e := GraphvizAddEdge(gv, "a", "b");
<graphviz edge (a, b)>
gap> GraphvizHead(e);
<graphviz node "a">

# doc/_Chapter_Full_Reference.xml:330-336
gap> gv := GraphvizGraph();;
gap> e := GraphvizAddEdge(gv, "a", "b");
<graphviz edge (a, b)>
gap> GraphvizTail(e);
<graphviz node "b">

# doc/_Chapter_Full_Reference.xml:358-363
gap> gv := GraphvizGraph();
<graphviz graph with 0 nodes and 0 edges>
gap> GraphvizSetName(gv, "newname");
<graphviz graph "newname" with 0 nodes and 0 edges>

# doc/_Chapter_Full_Reference.xml:379-386
gap> gv := GraphvizGraph();
<graphviz graph with 0 nodes and 0 edges>
gap> GraphvizAddNode(gv, "a");
<graphviz node "a">
gap> gv;
<graphviz graph with 1 node and 0 edges>

# doc/_Chapter_Full_Reference.xml:408-415
gap> gv := GraphvizGraph();
<graphviz graph with 0 nodes and 0 edges>
gap> GraphvizAddEdge(gv, "a", "b");
<graphviz edge (a, b)>
gap> gv;
<graphviz graph with 2 nodes and 1 edge>

# doc/_Chapter_Full_Reference.xml:433-434

# doc/_Chapter_Full_Reference.xml:461-462

# doc/_Chapter_Full_Reference.xml:481-488
gap> gv := GraphvizGraph();;
gap> GraphvizAddNode(gv, "a");;
gap> gv;
<graphviz graph with 1 node and 0 edges>
gap> GraphvizRemoveNode(gv, "a");
<graphviz graph with 0 nodes and 0 edges>

# doc/_Chapter_Full_Reference.xml:501-502

# doc/_Chapter_Full_Reference.xml:517-524
gap> gv := GraphvizGraph();;
gap> GraphvizAddEdge(gv, "a", "b");;
gap> gv;
<graphviz graph with 2 nodes and 1 edge>
gap> GraphvizRemoveEdges(gv, "a", "b");
<graphviz graph with 2 nodes and 0 edges>

# doc/_Chapter_Full_Reference.xml:547-548

# doc/_Chapter_Full_Reference.xml:566-567

# doc/_Chapter_Full_Reference.xml:582-583

# doc/_Chapter_Full_Reference.xml:599-600

# doc/_Chapter_Full_Reference.xml:619-620

# doc/_Chapter_Full_Reference.xml:634-635

# doc/_Chapter_Full_Reference.xml:750-751

# doc/_Chapter_Full_Reference.xml:768-769

# doc/_Chapter_Full_Reference.xml:784-785

# doc/_Chapter_Full_Reference.xml:798-799

#
gap> STOP_TEST("graphvizforgap01.tst", 1);
