# GraphvizForGAP, chapter 2
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("graphvizforgap01.tst");

# gap/dot.gd:224-235
gap> gv := GraphvizGraph("GraphyMcGraphFace");
<graphviz graph "GraphyMcGraphFace" with 0 nodes and 0 edges>
gap> GraphvizName(gv);
"GraphyMcGraphFace"
gap> GraphvizGraph(666);
<graphviz graph "666" with 0 nodes and 0 edges>
gap> gv := GraphvizGraph();
<graphviz graph with 0 nodes and 0 edges>
gap> GraphvizName(gv);
""

# gap/dot.gd:263-274
gap> gv := GraphvizDigraph("GraphyMcGraphFace");
<graphviz digraph "GraphyMcGraphFace" with 0 nodes and 0 edges>
gap> GraphvizName(gv);
"GraphyMcGraphFace"
gap> GraphvizDigraph(666);
<graphviz digraph "666" with 0 nodes and 0 edges>
gap> gv := GraphvizDigraph();
<graphviz digraph with 0 nodes and 0 edges>
gap> GraphvizName(gv);
""

# gap/dot.gd:289-300
gap> dot := GraphvizDigraph("The Round Table");;
gap> GraphvizName(dot);
"The Round Table"
gap> n := GraphvizSetAttr(GraphvizAddNode(dot, "A"), "label", "King Arthur");
<graphviz node "A">
gap> GraphvizName(n);
"A"
gap> e := GraphvizAddEdge(dot, "A", "B");;
gap> GraphvizName(e);
"(A, B)"

# gap/dot.gd:325-326

# gap/dot.gd:332-333

# gap/dot.gd:340-341

# gap/dot.gd:351-352

# gap/dot.gd:363-364

# gap/dot.gd:377-378

# gap/dot.gd:384-385

# gap/dot.gd:397-398

# gap/dot.gd:406-407

# gap/dot.gd:425-426

# gap/dot.gd:438-439

# gap/dot.gd:462-463

# gap/dot.gd:481-482

# gap/dot.gd:489-490

# gap/dot.gd:499-500

# gap/dot.gd:516-517

# gap/dot.gd:531-532

# gap/dot.gd:539-540

# gap/dot.gd:548-549

# gap/dot.gd:559-560

# gap/dot.gd:572-573

# gap/dot.gd:583-584

# gap/dot.gd:593-594

# gap/dot.gd:605-606

# gap/dot.gd:616-617

#
gap> STOP_TEST("graphvizforgap01.tst", 1);
